[project]
name = "repoutils"
version = "0.1.0"
description = "repo utils"
readme = "README.md"
authors = [
    { name = "Xudong Zhang", email = "zhangxudong@lixiang.com" }
]
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.4",
    "sysutils",
]

[[tool.uv.index]]
# url = "https://mirrors.aliyun.com/pypi/simple"
url = "https://artifactory.ep.chehejia.com/artifactory/api/pypi/pypi-remote/simple"
default = true

[tool.uv.sources]
sysutils = { path = "../sysutils", editable = true }


[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
testpaths = ["tests"]

[dependency-groups]
dev = [
    "coverage>=7.8.0",
    "pytest>=8.3.4",
    "pytest-cov>=6.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ['repoutils']
