[project]
name = "datautils"
version = "0.1.0"
description = "analysis"
readme = "README.md"
authors = [
    { name = "Xudong Zhang", email = "zhangxudong@lixiang.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "commonlibs",
]

[[tool.uv.index]]
# url = "https://mirrors.aliyun.com/pypi/simple"
url = "https://artifactory.ep.chehejia.com/artifactory/api/pypi/pypi-remote/simple"
default = true

[tool.uv.sources]
commonlibs = { path = "../commonlibs", editable = true }


[tool.pytest.ini_options]
log_cli = "true"
log_cli_level = "DEBUG"
testpaths = ["tests"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.1.1",
]

[tool.hatch.build.targets.wheel]
packages = ['datautils']
