[project]
name = "externalapis"
version = "0.1.0"
description = "api for portal, lpai..."
readme = "README.md"
authors = [
    { name = "Xudong Zhang", email = "zhangxudong@lixiang.com" }
]
requires-python = ">=3.10"
dependencies = [
    "httpx[http2]>=0.28.1",
    "commonlibs",
    "requests>=2.32.5",
]

[[tool.uv.index]]
url = "https://artifactory.ep.chehejia.com/artifactory/api/pypi/pypi-remote/simple"
default = true

[tool.uv.sources]
commonlibs = { path = "../commonlibs", editable = true }

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
testpaths = [".", "tests"]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.26.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.hatch.build.targets.wheel]
packages = ["externalapis"]
